import type { TdmMenuGroup } from "@/types/catalog";

/**
 * TDM homepage L2 tile slugs per industry group.
 * Order matches https://www.tdm.vn/ homepage blocks.
 */
export const TDM_HOMEPAGE_TILES: Record<TdmMenuGroup, string[]> = {
  "thiet-bi-ve-sinh": [
    "bon-cau",
    "bon-cau-dien-tu",
    "nap-bon-cau",
    "chau-lavabo",
    "voi-lavabo",
    "voi-cam-ung",
    "bon-tieu",
    "van-xa-tieu",
    "voi-sen",
    "sen-cay",
    "sen-am-tuong",
    "bon-tam",
    "voi-bon-tam",
    "phu-kien-phong-tam",
    "pheu-thoat-san",
    "voi-xit-ve-sinh",
  ],
  "thiet-bi-bep": [
    "bep-dien-tu",
    "bep-gas",
    "may-hut-mui",
    "lo-nuong",
    "lo-vi-song",
    "may-rua-chen",
    "tu-lanh",
    "voi-rua-chen",
  ],
  "thiet-bi-nuoc": [
    "bon-inox",
    "bon-nhua",
    "bon-cong-nghiep",
    "bon-tu-hoai",
    "nang-luong-mat-troi",
    "may-nuoc-nong",
    "may-loc-nuoc",
    "chau-rua-inox",
  ],
  "thiet-bi-khoa": [
    "khoa-dien-tu",
    "khoa-cua-chinh",
    "khoa-cua-phong",
    "khoa-bam-moc",
    "phu-kien-cua",
    "ket-sat",
  ],
  "thiet-bi-dien": [
    "cong-tac-o-cam",
    "den-led-chieu-sang",
    "thiet-bi-quat",
    "day-cap-dien",
    "tu-dien",
  ],
};

/** Map homepage tile slug → product listing category slug (for thumbnail lookup & links) */
export const TILE_TO_LISTING_SLUG: Record<string, string> = {
  "bon-cau": "bon-cau-bet-ve-sinh",
  "bon-cau-dien-tu": "bon-cau-thong-minh",
  "nap-bon-cau": "bon-cau-bet-ve-sinh",
  "chau-lavabo": "chau-rua-lavabo",
  "voi-lavabo": "voi-lavabo",
  "voi-cam-ung": "voi-rua-cam-ung",
  "bon-tieu": "bon-tieu-nam-nu",
  "van-xa-tieu": "van-xa-tieu",
  "voi-sen": "voi-sen-cay",
  "sen-cay": "voi-sen-cay",
  "sen-am-tuong": "voi-sen-tam-am-tuong",
  "bon-tam": "bon-tam",
  "voi-bon-tam": "bon-tam",
  "phu-kien-phong-tam": "phu-kien-phong-tam",
  "pheu-thoat-san": "phu-kien-phong-tam",
  "voi-xit-ve-sinh": "voi-xit-ve-sinh",
  "bep-dien-tu": "bep-dien-tu",
  "bep-gas": "bep-gas",
  "may-hut-mui": "may-hut-mui",
  "lo-nuong": "lo-nuong-da-nang",
  "lo-vi-song": "lo-vi-song",
  "may-rua-chen": "may-rua-chen-bat",
  "tu-lanh": "tu-lanh",
  "voi-rua-chen": "voi-bep-voi-rua-chen",
  "bon-inox": "bon-nuoc-inox",
  "bon-nhua": "bon-nuoc-nhua",
  "bon-cong-nghiep": "bon-nuoc-inox",
  "bon-tu-hoai": "bon-tu-hoai",
  "nang-luong-mat-troi": "may-nuoc-nong",
  "may-nuoc-nong": "may-nuoc-nong",
  "may-loc-nuoc": "may-loc-nuoc",
  "chau-rua-inox": "voi-bep-voi-rua-chen",
  "khoa-dien-tu": "khoa-dien-tu",
  "khoa-cua-chinh": "thiet-bi-khoa-cua",
  "khoa-cua-phong": "thiet-bi-khoa-cua",
  "khoa-bam-moc": "thiet-bi-khoa-cua",
  "phu-kien-cua": "thiet-bi-khoa-cua",
  "ket-sat": "thiet-bi-khoa-cua",
  "cong-tac-o-cam": "thiet-bi-ve-sinh",
  "den-led-chieu-sang": "thiet-bi-ve-sinh",
  "thiet-bi-quat": "thiet-bi-ve-sinh",
  "day-cap-dien": "thiet-bi-ve-sinh",
  "tu-dien": "thiet-bi-ve-sinh",
};

export function getListingSlugForTile(tileSlug: string): string {
  return TILE_TO_LISTING_SLUG[tileSlug] ?? tileSlug;
}
